# 地面数据
SURFACE: "SURF_CHN_MUL_HOR"
PRE_MIN: "SURF_CHN_PRE_MIN"
DSD: "SURF_WEA_CHN_RSD"
CMPA_HOR: "SURF_CMPA_FAST_5KM_3S"
CMPA_3HOR: "SURF_CMPA_FAST_5KM_3S_3HOR"
CMPA_DAY: "SURF_CMPA_FAST_5KM_DAY_3S"
CMPA_1KM_RT: "SURF_CMPAS_MUL_1KM_RT"
CMPA_1KM_NRT: "SURF_CMPA_MUL_1KM_NRT"

# 高空数据
UPPER_AIR: "UPAR_CHN_MUL_FTM"
WIND_PROFILER: "UPAR_WPR_HALFHOUR_NC_GLB"
THUNDER_CHN: "UPAR_ADTD_CHN_LIS"
MWR_PROD: "UPAR_CHN_MWR_PROD_MIN"
GPSMET: "UPAR_STA_GPSMET_VAP"

# === 数值预报
# -- 常用全球数值模式
CMA_GFS: "NAFP_FOR_FTM_GRAPES_CFSV2_NEHE"
ECMWF_HR: "NAFP_ECMF_C1D_GLB_FOR"
ECMWF_S: "NAFP_ECMF_C1D_GLB_FOR"
ECMWF_P: "NAFP_FOR_FTM_HIGH_EC_ANEA"
ECMWF_D1D: "NAFP_EC_HERS_D1D_ORI_ACHN"
ECMWF_C3E: "NAFP_C3E_FOR_FTM_LOW_ASI"
NCEP_GFS: "NAFP_KWBC_GFS_FOR_0P25_GLB"
GERMAN_HR: "NAFP_FOR_FTM_GER_GLB"
JAPAN_MR: "NAFP_FOR_FTM_HIGH_JAP_NEHE"

# 常用中尺度区域数值模式
CMA_MESO: "NAFP_GRAPES_MESO_3KM_ORI"
CMA_SH3: "NAFP_SURFACE_FOR_WARR_NRT_3KM_ECH_GRIB"
CMA_SH9: "NAFP_WARMS_9KM_ECH"
CMA_TYM: "NAFP_GRAPES_TYM_9KM_ORI"

# 实况分析产品
ART_1KM: "NAFP_HRCLDAS_CHN_1KM_RT"
CLDAS_H: "NAFP_GRID_ANA_REALTIME_HOR_CHN"
CLDAS_D: "NAFP_GRID_ANA_REALTIME_DAY_CHN"

# 国家局预报业务下发产品
SCMOC: "NAFP_NWFD_SCMOC"
SMERGE: "NAFP_NWFD_SMERGE"

# 卫星观测
SATE_FY2G: "SATE_GEO_IMAGE_LATLON_F2G"

# 台风
TYPHOON: "SEVP_WEFC_TYP_WT"